# FIXME: not working when fetching repository
name: update-submodules

on:
  workflow_call:
    secrets:
      ACTIONS_GITHUB_TOKEN:
        required: true
        description: "GitHub token for checkout and PR creation"

jobs:
  update-submodules:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          submodules: true
          persist-credentials: false

      - name: Update submodules
        run: git submodule update --remote --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "contents: update submodule"
          title: "contents: update submodule"
